import styles from '../styles/Home.module.css'
import Head from 'next/head'
import React from 'react'

import Link from 'next/link'
import {signIn, signOut, useSession} from 'next-auth/client'

export default function Home() {
  const[session, loading] = useSession()
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
          {!session && <>
          Not signed in <br/>
          <button onClick={() => signIn()}>Sign in</button>
          </>}
           
          {session && <>
          Signed in as {session.user.name} <br/>
         
          <button onClick={() => signOut()}>Sign out</button>
          </>}
    </div>
  )
}

